/*
 * BrowserCat API
 * Providing purr-fect headless browser access via utility endpoints and direct websocket connections.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@browsercat.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BadRequestErrorFieldsInner
 */
public class BadRequestErrorFieldsInnerTest {
    private final BadRequestErrorFieldsInner model = new BadRequestErrorFieldsInner();

    /**
     * Model tests for BadRequestErrorFieldsInner
     */
    @Test
    public void testBadRequestErrorFieldsInner() {
        // TODO: test BadRequestErrorFieldsInner
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'expected'
     */
    @Test
    public void expectedTest() {
        // TODO: test expected
    }

    /**
     * Test the property 'received'
     */
    @Test
    public void receivedTest() {
        // TODO: test received
    }

    /**
     * Test the property 'validation'
     */
    @Test
    public void validationTest() {
        // TODO: test validation
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

}
