/*
 * BrowserCat API
 * Providing purr-fect headless browser access via utility endpoints and direct websocket connections.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@browsercat.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Invoice
 */
public class InvoiceTest {
    private final Invoice model = new Invoice();

    /**
     * Model tests for Invoice
     */
    @Test
    public void testInvoice() {
        // TODO: test Invoice
    }

    /**
     * Test the property 'invId'
     */
    @Test
    public void invIdTest() {
        // TODO: test invId
    }

    /**
     * Test the property 'subId'
     */
    @Test
    public void subIdTest() {
        // TODO: test subId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'amountDue'
     */
    @Test
    public void amountDueTest() {
        // TODO: test amountDue
    }

    /**
     * Test the property 'amountPaid'
     */
    @Test
    public void amountPaidTest() {
        // TODO: test amountPaid
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'totalDiscount'
     */
    @Test
    public void totalDiscountTest() {
        // TODO: test totalDiscount
    }

    /**
     * Test the property 'totalTax'
     */
    @Test
    public void totalTaxTest() {
        // TODO: test totalTax
    }

    /**
     * Test the property 'billedAt'
     */
    @Test
    public void billedAtTest() {
        // TODO: test billedAt
    }

    /**
     * Test the property 'stripeInvId'
     */
    @Test
    public void stripeInvIdTest() {
        // TODO: test stripeInvId
    }

    /**
     * Test the property 'stripeSubId'
     */
    @Test
    public void stripeSubIdTest() {
        // TODO: test stripeSubId
    }

    /**
     * Test the property 'stripeCusId'
     */
    @Test
    public void stripeCusIdTest() {
        // TODO: test stripeCusId
    }

}
