/*
 * BrowserCat API
 * Providing purr-fect headless browser access via utility endpoints and direct websocket connections.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@browsercat.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ServerCheckHealthStatusResponse
 */
public class ServerCheckHealthStatusResponseTest {
    private final ServerCheckHealthStatusResponse model = new ServerCheckHealthStatusResponse();

    /**
     * Model tests for ServerCheckHealthStatusResponse
     */
    @Test
    public void testServerCheckHealthStatusResponse() {
        // TODO: test ServerCheckHealthStatusResponse
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'uptime'
     */
    @Test
    public void uptimeTest() {
        // TODO: test uptime
    }

}
