/*
 * BrowserCat API
 * Providing purr-fect headless browser access via utility endpoints and direct websocket connections.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@browsercat.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Subscription
 */
public class SubscriptionTest {
    private final Subscription model = new Subscription();

    /**
     * Model tests for Subscription
     */
    @Test
    public void testSubscription() {
        // TODO: test Subscription
    }

    /**
     * Test the property 'subId'
     */
    @Test
    public void subIdTest() {
        // TODO: test subId
    }

    /**
     * Test the property 'tier'
     */
    @Test
    public void tierTest() {
        // TODO: test tier
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'periodUnit'
     */
    @Test
    public void periodUnitTest() {
        // TODO: test periodUnit
    }

    /**
     * Test the property 'periodCount'
     */
    @Test
    public void periodCountTest() {
        // TODO: test periodCount
    }

    /**
     * Test the property 'periodStartsAt'
     */
    @Test
    public void periodStartsAtTest() {
        // TODO: test periodStartsAt
    }

    /**
     * Test the property 'periodEndsAt'
     */
    @Test
    public void periodEndsAtTest() {
        // TODO: test periodEndsAt
    }

    /**
     * Test the property 'anchoredAt'
     */
    @Test
    public void anchoredAtTest() {
        // TODO: test anchoredAt
    }

    /**
     * Test the property 'canceledAt'
     */
    @Test
    public void canceledAtTest() {
        // TODO: test canceledAt
    }

    /**
     * Test the property 'resumedAt'
     */
    @Test
    public void resumedAtTest() {
        // TODO: test resumedAt
    }

    /**
     * Test the property 'pausedAt'
     */
    @Test
    public void pausedAtTest() {
        // TODO: test pausedAt
    }

    /**
     * Test the property 'stripeSubId'
     */
    @Test
    public void stripeSubIdTest() {
        // TODO: test stripeSubId
    }

    /**
     * Test the property 'stripeCusId'
     */
    @Test
    public void stripeCusIdTest() {
        // TODO: test stripeCusId
    }

}
