/*
 * BrowserCat API
 * Providing purr-fect headless browser access via utility endpoints and direct websocket connections.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@browsercat.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UsageBucket
 */
public class UsageBucketTest {
    private final UsageBucket model = new UsageBucket();

    /**
     * Model tests for UsageBucket
     */
    @Test
    public void testUsageBucket() {
        // TODO: test UsageBucket
    }

    /**
     * Test the property 'usageBucketId'
     */
    @Test
    public void usageBucketIdTest() {
        // TODO: test usageBucketId
    }

    /**
     * Test the property 'keyId'
     */
    @Test
    public void keyIdTest() {
        // TODO: test keyId
    }

    /**
     * Test the property 'clerkOrgId'
     */
    @Test
    public void clerkOrgIdTest() {
        // TODO: test clerkOrgId
    }

    /**
     * Test the property 'clerkUserId'
     */
    @Test
    public void clerkUserIdTest() {
        // TODO: test clerkUserId
    }

    /**
     * Test the property 'bucket'
     */
    @Test
    public void bucketTest() {
        // TODO: test bucket
    }

    /**
     * Test the property 'method'
     */
    @Test
    public void methodTest() {
        // TODO: test method
    }

    /**
     * Test the property 'endpoint'
     */
    @Test
    public void endpointTest() {
        // TODO: test endpoint
    }

    /**
     * Test the property 'credits'
     */
    @Test
    public void creditsTest() {
        // TODO: test credits
    }

    /**
     * Test the property 'countSuccess'
     */
    @Test
    public void countSuccessTest() {
        // TODO: test countSuccess
    }

    /**
     * Test the property 'countFailure'
     */
    @Test
    public void countFailureTest() {
        // TODO: test countFailure
    }

    /**
     * Test the property 'durationSuccess'
     */
    @Test
    public void durationSuccessTest() {
        // TODO: test durationSuccess
    }

    /**
     * Test the property 'durationFailure'
     */
    @Test
    public void durationFailureTest() {
        // TODO: test durationFailure
    }

    /**
     * Test the property 'durationMin'
     */
    @Test
    public void durationMinTest() {
        // TODO: test durationMin
    }

    /**
     * Test the property 'durationMax'
     */
    @Test
    public void durationMaxTest() {
        // TODO: test durationMax
    }

    /**
     * Test the property 'durationMean'
     */
    @Test
    public void durationMeanTest() {
        // TODO: test durationMean
    }

    /**
     * Test the property 'durationStd'
     */
    @Test
    public void durationStdTest() {
        // TODO: test durationStd
    }

}
