/*
 * BrowserCat API
 * Providing purr-fect headless browser access via utility endpoints and direct websocket connections.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@browsercat.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UsageSessionPublic
 */
public class UsageSessionPublicTest {
    private final UsageSessionPublic model = new UsageSessionPublic();

    /**
     * Model tests for UsageSessionPublic
     */
    @Test
    public void testUsageSessionPublic() {
        // TODO: test UsageSessionPublic
    }

    /**
     * Test the property 'usageSessionId'
     */
    @Test
    public void usageSessionIdTest() {
        // TODO: test usageSessionId
    }

    /**
     * Test the property 'clerkOrgId'
     */
    @Test
    public void clerkOrgIdTest() {
        // TODO: test clerkOrgId
    }

    /**
     * Test the property 'clerkUserId'
     */
    @Test
    public void clerkUserIdTest() {
        // TODO: test clerkUserId
    }

    /**
     * Test the property 'keyId'
     */
    @Test
    public void keyIdTest() {
        // TODO: test keyId
    }

    /**
     * Test the property 'method'
     */
    @Test
    public void methodTest() {
        // TODO: test method
    }

    /**
     * Test the property 'endpoint'
     */
    @Test
    public void endpointTest() {
        // TODO: test endpoint
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'machineId'
     */
    @Test
    public void machineIdTest() {
        // TODO: test machineId
    }

    /**
     * Test the property 'machineRegion'
     */
    @Test
    public void machineRegionTest() {
        // TODO: test machineRegion
    }

    /**
     * Test the property 'browserType'
     */
    @Test
    public void browserTypeTest() {
        // TODO: test browserType
    }

    /**
     * Test the property 'browserVersion'
     */
    @Test
    public void browserVersionTest() {
        // TODO: test browserVersion
    }

    /**
     * Test the property 'agentType'
     */
    @Test
    public void agentTypeTest() {
        // TODO: test agentType
    }

    /**
     * Test the property 'agentVersion'
     */
    @Test
    public void agentVersionTest() {
        // TODO: test agentVersion
    }

    /**
     * Test the property 'startedAt'
     */
    @Test
    public void startedAtTest() {
        // TODO: test startedAt
    }

    /**
     * Test the property 'endedAt'
     */
    @Test
    public void endedAtTest() {
        // TODO: test endedAt
    }

    /**
     * Test the property 'sessionId'
     */
    @Test
    public void sessionIdTest() {
        // TODO: test sessionId
    }

}
