/*
 * BrowserCat API
 * Providing purr-fect headless browser access via utility endpoints and direct websocket connections.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@browsercat.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.ServerCheckHealthStatusResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ServerApi
 */
@Disabled
public class ServerApiTest {

    private static ServerApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ServerApi(apiClient);
    }

    /**
     * Show server health
     *
     * Lightweight endpoint to check server health.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkHealthStatusTest() throws ApiException {
        ServerCheckHealthStatusResponse response = api.checkHealthStatus()
                .execute();
        // TODO: test validations
    }

    /**
     * Show server metrics
     *
     * Returns server metrics in Prometheus format. Use this endpoint to monitor server health.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void showMetricsTest() throws ApiException {
        api.showMetrics()
                .execute();
        // TODO: test validations
    }

}
